theme: jekyll-theme-hacker

plugins:
  - jekyll-sitemap
  
 # Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  
  # Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "kontakt@martin-leipert.de"
  github: martinleipert
  twitter: martinleipert
  scholar: tnSLeQcAAAAJ 
#  reddit: yourname
  linkedin: martin-leipert-6b3723140
  xing: Martin_Leipert2
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
  instagram: martinleipert
#  youtube: user/deanat78
#  spotify: yourname
  telephone: +49 1577 8309855
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname